# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("* {\n"
"    font-family: \"Airbnb Cereal\", Arial, sans-serif;\n"
"}\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black; /* 设置按钮文字颜色 */\n"
"    border: 1px solid #CCCCCC; \n"
"    border-radius: 10px;\n"
"    padding: 5px; \n"
"    font: 15pt;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #50B56A; /* 按钮按下时的背景颜色 */\n"
"}\n"
"QMainWindow {\n"
"    background-color: #EFEFEF;\n"
"}\n"
"QLabel {\n"
"    font: 20pt;\n"
"}\n"
"Line{\n"
"    background-color: #4362F0; /* 设置线条颜色 */\n"
"    border: none; /* 移除默认边框 */\n"
"    min-height: 3px; /* 设置线条粗细 */\n"
"    max-height: 3px; /* 设置线条粗细 */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(198, 198, 198);\n"
"    border-radius: 10px;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget1 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(10, -1, 10, 1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MenuButton = QtWidgets.QPushButton(self.widget1)
        self.MenuButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}")
        self.MenuButton.setObjectName("MenuButton")
        self.horizontalLayout.addWidget(self.MenuButton)
        self.ViewButton = QtWidgets.QPushButton(self.widget1)
        self.ViewButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}")
        self.ViewButton.setObjectName("ViewButton")
        self.horizontalLayout.addWidget(self.ViewButton)
        self.ContriolButton = QtWidgets.QPushButton(self.widget1)
        self.ContriolButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}")
        self.ContriolButton.setObjectName("ContriolButton")
        self.horizontalLayout.addWidget(self.ContriolButton)
        self.horizontalLayout_2.addWidget(self.widget1)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setStyleSheet("QWidget {\n"
"    background-color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(20, 10, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StatusLabel = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusLabel.sizePolicy().hasHeightForWidth())
        self.StatusLabel.setSizePolicy(sizePolicy)
        self.StatusLabel.setStyleSheet("QLabel {\n"
"    background-color: #4362F0;\n"
"    color: white;\n"
"    text-align: center; \n"
"    padding: 5px;\n"
"}")
        self.StatusLabel.setObjectName("StatusLabel")
        self.verticalLayout.addWidget(self.StatusLabel)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget2)
        self.textBrowser_2.setStyleSheet("QTextBrowser {\n"
"    background-color: white;\n"
"}")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout.addWidget(self.textBrowser_2)
        self.WarningLabel = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WarningLabel.sizePolicy().hasHeightForWidth())
        self.WarningLabel.setSizePolicy(sizePolicy)
        self.WarningLabel.setStyleSheet("QLabel {\n"
"    background-color: #F0BF43;\n"
"    color: white;\n"
"    text-align: center; \n"
"    padding: 5px;\n"
"}")
        self.WarningLabel.setObjectName("WarningLabel")
        self.verticalLayout.addWidget(self.WarningLabel)
        self.warningTable = QtWidgets.QTableWidget(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Airbnb Cereal")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.warningTable.setFont(font)
        self.warningTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.warningTable.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"}")
        self.warningTable.setLineWidth(5)
        self.warningTable.setRowCount(1)
        self.warningTable.setObjectName("warningTable")
        self.warningTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.warningTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.warningTable.setHorizontalHeaderItem(1, item)
        self.warningTable.horizontalHeader().setCascadingSectionResizes(True)
        self.warningTable.horizontalHeader().setDefaultSectionSize(125)
        self.warningTable.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.warningTable)
        self.WarningSetting = QtWidgets.QPushButton(self.widget2)
        self.WarningSetting.setAutoFillBackground(False)
        self.WarningSetting.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}")
        self.WarningSetting.setObjectName("WarningSetting")
        self.verticalLayout.addWidget(self.WarningSetting)
        self.WarningHis = QtWidgets.QPushButton(self.widget2)
        self.WarningHis.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}")
        self.WarningHis.setObjectName("WarningHis")
        self.verticalLayout.addWidget(self.WarningHis)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 6)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.horizontalLayout_3.addWidget(self.widget2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("QStackedWidget {\n"
"rgb(255, 255, 255)\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_3.setStyleSheet("QTextBrowser {\n"
"    border : white;\n"
"    padding : 5px;\n"
"\n"
"}\n"
"")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalLayout_12.addWidget(self.textBrowser_3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget3 = QtWidgets.QWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget3.sizePolicy().hasHeightForWidth())
        self.widget3.setSizePolicy(sizePolicy)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(200, 200))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_6.sizePolicy().hasHeightForWidth())
        self.textBrowser_6.setSizePolicy(sizePolicy)
        self.textBrowser_6.setMaximumSize(QtCore.QSize(15000, 600))
        self.textBrowser_6.setStyleSheet("QTextBrowser {\n"
"    border: white;\n"
"}\n"
"")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.verticalLayout_4.addWidget(self.textBrowser_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PosDashboard = QtWidgets.QWidget(self.widget3)
        self.PosDashboard.setObjectName("PosDashboard")
        self.horizontalLayout_4.addWidget(self.PosDashboard)
        self.SpeedDashboard = QtWidgets.QWidget(self.widget3)
        self.SpeedDashboard.setObjectName("SpeedDashboard")
        self.horizontalLayout_4.addWidget(self.SpeedDashboard)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.PowerDashboard = QtWidgets.QWidget(self.widget3)
        self.PowerDashboard.setObjectName("PowerDashboard")
        self.verticalLayout_3.addWidget(self.PowerDashboard)
        self.currentLineChart = QtWidgets.QWidget(self.widget3)
        self.currentLineChart.setObjectName("currentLineChart")
        self.verticalLayout_3.addWidget(self.currentLineChart)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.setStretch(2, 2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11.addWidget(self.widget3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(200, 200))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Airbnb Cereal")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_8.setFont(font)
        self.textBrowser_8.setStyleSheet("QTextBrowser {\n"
"    border: 2px solid white;\n"
"}")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.verticalLayout_6.addWidget(self.textBrowser_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableWidget = QtWidgets.QTableWidget(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Airbnb Cereal")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    border: white;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_9.addWidget(self.tableWidget)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.controlButton_acc = QtWidgets.QPushButton(self.page_3)
        self.controlButton_acc.setObjectName("controlButton_acc")
        self.verticalLayout_7.addWidget(self.controlButton_acc)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_7.addWidget(self.pushButton_7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_8.addWidget(self.pushButton_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_8.addWidget(self.pushButton_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.horizontalLayout_7.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Airbnb Cereal")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.lineEdit = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: white;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 3)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_8)
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 9)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "[Logo]"))
        self.MenuButton.setText(_translate("MainWindow", "Menu"))
        self.ViewButton.setText(_translate("MainWindow", "View"))
        self.ContriolButton.setText(_translate("MainWindow", "Control"))
        self.StatusLabel.setText(_translate("MainWindow", "  Status  "))
        self.WarningLabel.setText(_translate("MainWindow", "  Warnings  "))
        item = self.warningTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.warningTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        self.WarningSetting.setText(_translate("MainWindow", "Settings"))
        self.WarningHis.setText(_translate("MainWindow", "History"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Airbnb Cereal\',\'Arial\',\'sans-serif\'; font-size:10.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<h2 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"markdown-section--18\"></a><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">D</span><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">escription</span></h2>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; font-style:italic; color:#000000;\">This project is a stm32 based control system with following features:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:14pt; font-weight:600; color:#000000;\">1.Motor monitoring:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\">Three-phase current (Ia, Ib, Ic) acquisition</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\">Speed feedback and control</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\">Position feedback and control</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">2. Motor control</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\">Data transmission via UART (576000 baud rate)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\">VOFA+ compatible for debugging and monitoring</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\">Closed-loop control:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\">Current loop control</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\">Speed loop control</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe WPC\',\'Segoe UI\',\'sans-serif\'; font-size:11pt; color:#000000;\">Position loop control</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "[pic]"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Airbnb Cereal\',\'Arial\',\'sans-serif\'; font-size:10.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">id:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">type:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">current:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "[pic]"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Airbnb Cereal\',\'Arial\',\'sans-serif\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400;\">id:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400;\">type:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400;\">current:</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "time"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Position"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Velocity"))
        self.controlButton_acc.setText(_translate("MainWindow", "Accelerate"))
        self.pushButton_7.setText(_translate("MainWindow", "Decelerate"))
        self.pushButton_6.setText(_translate("MainWindow", "Stop"))
        self.pushButton_8.setText(_translate("MainWindow", "Turnover"))
        self.label_3.setText(_translate("MainWindow", "Target velocity"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "please enter here"))
